export const productsData = [
  {
    id: 1,
    name: "ZWILLING",
    description: "МАНИКЮРНЫЙ НАБОР 3 ПР. ЧЕРНЫЙ ZWILLING BEAUTY PREMIUM",
    price: 19140.0,
    image: "/p1.webp",
    isNew: true,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 2,
    name: "ZWILLING",
    description: "МАНИКЮРНЫЙ НАБОР 5 ПР. ЧЕРНЫЙ ZWILLING BEAUTY PREMIU",
    price: 34740.0,
    image: "/p2.webp",
    isNew: true,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 3,
    name: "ZWILLING",
    description: "МАНИКЮРНЫЙ НАБОР 12 ПР. ЧЕРНЫЙ ZWILLING BEAUTY PREMIUM",
    price: 85740.0,
    image: "/p3.webp",
    isNew: true,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 4,
    name: "ZWILLING",
    description: "ПИНЦЕТ ДЛЯ ОБРЕЗАНИЯ КУТИКУЛЫ ZWILLING BEAUTY PREMIUM",
    price: 4780.0,
    image: "/p4.webp",
    isNew: true,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 5,
    name: "ZWILLING",
    description: "НАБОР СТОЛОВЫХ ПРИБОРОВ ABERDEEN 30 ПР.",
    price: 32200.0,
    image: "/p5.webp",
    isNew: true,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 6,
    name: "ZWILLING",
    description: "НАБОР СТОЛОВЫХ ПРИБОРОВ SWING 30 ПР.",
    price: 32200.0,
    image: "/p6.webp",
    isNew: true,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 7,
    name: "ZWILLING",
    description: "НАБОР СТОЛОВЫХ ПРИБОРОВ",
    price: 55400.0,
    image: "/p1.webp",
    isNew: true,
    isFavorite: false,
    quantity: 0,
  },
];
export const bestsellerData = [
  {
    id: 1,
    name: "ZWILLING",
    description: "МАНИКЮРНЫЙ НАБОР 3 ПР. ЧЕРНЫЙ ZWILLING BEAUTY PREMIUM",
    price: 19140.0,
    image: "/be1.webp",
    isNew: false,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 2,
    name: "ZWILLING",
    description: "МАНИКЮРНЫЙ НАБОР 5 ПР. ЧЕРНЫЙ ZWILLING BEAUTY PREMIU",
    price: 34740.0,
    image: "/be2.webp",
    isNew: false,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 3,
    name: "ZWILLING",
    description: "МАНИКЮРНЫЙ НАБОР 12 ПР. ЧЕРНЫЙ ZWILLING BEAUTY PREMIUM",
    price: 85740.0,
    image: "/be3.webp",
    isNew: false,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 4,
    name: "ZWILLING",
    description: "ПИНЦЕТ ДЛЯ ОБРЕЗАНИЯ КУТИКУЛЫ ZWILLING BEAUTY PREMIUM",
    price: 4780.0,
    image: "/be4.webp",
    isNew: false,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 5,
    name: "ZWILLING",
    description: "НАБОР СТОЛОВЫХ ПРИБОРОВ ABERDEEN 30 ПР.",
    price: 32200.0,
    image: "/be4.webp",
    isNew: false,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 6,
    name: "ZWILLING",
    description: "НАБОР СТОЛОВЫХ ПРИБОРОВ SWING 30 ПР.",
    price: 32200.0,
    image: "/p6.webp",
    isNew: false,
    isFavorite: false,
    quantity: 0,
  },
  {
    id: 7,
    name: "ZWILLING",
    description: "НАБОР СТОЛОВЫХ ПРИБОРОВ",
    price: 55400.0,
    image: "/p1.webp",
    isNew: false,
    isFavorite: false,
    quantity: 0,
  },
];

export const menuItems = [
  {
    title: "ЛИЧНЫЙ КАБИНЕТ",
    path: "#",
  },
  {
    title: "ТЕКУЩИЕ ЗАКАЗЫ",
    path: "#",
  },
  {
    title: "ЛИЧНЫЕ ДАННЫЕ",
    path: "#",
  },
  {
    title: "ВЫЙТИ",
    path: "#",
  },
];

export const popularCategories = [
  { name: "Посуда", href: "#" },
  { name: "Маникюрные наборы", href: "#" },
  { name: "Сковороды", href: "#" },
  { name: "Кастрюли", href: "#" },
  { name: "Чугунная посуда", href: "#" },
];
